### Урок 1. Линейное пространство. Основные понятия. Часть 1

#### Задание 1
Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц: <br>
а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; <br>
б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; <br>
в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; <br>
г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Решение: <br>
а) $AB$ — произведение не определено; $BA$ — произведение не определено. <br>
б) $AB$ — произведение определено, размерность полученной матрицы 2×3; $BA$ — произведение не определено. <br>
в) $AB$ — произведение определено, размерность полученной матрицы 8×8; $BA$ — произведение определено, размерность полученной матрицы 3×3. <br>
г) $AB$; $BA$ — оба произведения определены, размерность полученной матрицы 4×4.

#### Задание 2
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Решение: <br>

In [1]:
import numpy as np

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
sum_a_b = a + b
sum_a_b

array([[ 5, -3],
       [ 3,  5]])

In [3]:
prod_a_b = np.dot(a, b)
prod_a_b

array([[  4, -11],
       [ 12,  -3]])

#### Задание 3
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

Решение: <br>

In [4]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
result = (3 * a) + (-2 * b) + (4 * c)
result

array([[ 11,  -5],
       [  9, -12]])

#### Задание 4
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

Решение: <br>

In [5]:
a = np.array([[4, 1], [5, -2], [2, 3]])
a_transposed = a.T
a_transposed

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [6]:
result = np.dot(a, a_transposed)
result

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
result = np.dot(a_transposed, a)
result

array([[45,  0],
       [ 0, 14]])

#### Задание 5
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Решение: <br>

In [8]:
def multiply_matrix(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        return ValueError('Произведение матриц не определено')
    result = [[0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

Проверка: <br>

In [9]:
x = np.array([[1, -9], [5, 0], [3, 5]])
y = np.array([[9, 1], [5, 3]])
print(f'Матрица Х:\n {x}')
print(f'Матрица Y:\n {y}')
print(f'Результат метода NumPy: \n {np.dot(x, y)}')
print(f'Результат собственного метода: \n {multiply_matrix(x, y)}')

Матрица Х:
 [[ 1 -9]
 [ 5  0]
 [ 3  5]]
Матрица Y:
 [[9 1]
 [5 3]]
Результат метода NumPy: 
 [[-36 -26]
 [ 45   5]
 [ 52  18]]
Результат собственного метода: 
 [[-36, -26], [45, 5], [52, 18]]


### Урок 1. Линейное пространство. Основные понятия. Часть 2

#### Задание 1
Вычислить определитель: <br>
a) 
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$
<br>
<br>
б) 
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
<br>
<br>
в) 
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Решение: <br>

а) 

$det = sinx * sinx - (cosx * (-cosx)) = sin^2x + cos^2x = 1$

б)

In [10]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
det_a = np.linalg.det(a)
det_a

180.0

в)

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det_a = np.linalg.det(a)
det_a

0.0

#### Задание 2
Определитель матрицы $A$ равен $4$. Найти: <br>
а) $det(A^{2})$; <br>
б) $det(A^{T})$; <br>
в) $det(2A)$.

Решение: <br>

а) $det(A^{2}) = det(AA) = det(A)*det(a) = 4 * 4 = 16$.

б) $det(A^{T}) = det(A) = 4$.

в) $det(2A) = det(A) * 2^n = 4 * 2^n$, n - количество строк в матрице.

#### Задание 3
Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Решение: <br>

In [12]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
det_a = np.linalg.det(a)
det_a

0.0

Определитель матрицы равен нулю, следовательно, матрица вырожденная.

#### Задание 4
Найти ранг матрицы: <br>
а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$
<br>
<br>
   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Решение: <br>

In [13]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
result_a = np.linalg.matrix_rank(a)
result_a

2

In [14]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
result_b = np.linalg.matrix_rank(b)
result_b

3