### Урок 4. Системы линейных уравнений. Часть 1

In [1]:
import numpy as np

# Задание 5
# Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

# Решение:
# Реализуем алгоритм решения СЛАУ методом LU-разложения.

def decompose_to_LU(a):
    """Decompose matrix of coefficients to L and U matrices.
     L and U triangular matrices will be represented in a single n x n matrix.
    :param a: numpy matrix of coefficients
    :return: numpy LU matrix
    """
    # create emtpy LU-matrix
    lu_matrix = np.matrix(np.zeros([a.shape[0], a.shape[1]]))
    n = a.shape[0]

    for k in range(n):
        # calculate all residual k-row elements
        for j in range(k, n):
            lu_matrix[k, j] = a[k, j] - lu_matrix[k, :k] * lu_matrix[:k, j]
        # calculate all residual k-column elemetns
        for i in range(k + 1, n):
            lu_matrix[i, k] = (a[i, k] - lu_matrix[i, : k] * lu_matrix[: k, k]) / lu_matrix[k, k]

    return lu_matrix

def get_L(m):
    """Get triangular L matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular L matrix
    """
    L = m.copy()
    for i in range(L.shape[0]):
            L[i, i] = 1
            L[i, i+1 :] = 0
    return np.matrix(L)


def get_U(m):
    """Get triangular U matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular U matrix
    """
    U = m.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return U

def solve_LU(lu_matrix, b):
    """Solve system of equations from given LU-matrix and vector b of absolute terms.
    :param lu_matrix: numpy LU-matrix
    :param b: numpy matrix of absolute terms [n x 1]
    :return: numpy matrix of answers [n x 1]
    """
    # get supporting vector y
    y = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(y.shape[0]):
        y[i, 0] = b[i, 0] - lu_matrix[i, :i] * y[:i]

    # get vector of answers x
    x = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(1, x.shape[0] + 1):
        x[-i, 0] = (y[-i] - lu_matrix[-i, -i:] * x[-i:, 0] )/ lu_matrix[-i, -i]

    return x

#### Задание 1
Решить систему уравнений методом Гаусса: <br>
$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

Решение: <br>
Запишем расширенную матрицу системы. <br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$ <br>
<br>
Отнимем из второй строки первую, умноженную на 2. <br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
0 & -1 & 1 &5\\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$ <br>
<br>
Отнимем из третьей строки первую. <br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
0 & -1 & 1 & 5\\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$ <br>
<br>
Система имеет бесконечное кол-во решений. <br>
Поделим третью строку на 3. <br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
0 & -1 & 1 & 5\\
0 & 0 & -\frac{2}{3} & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
\frac{4}{3}
\end{matrix}
\end{pmatrix}$ <br>
<br>
Оставшаяся матрица соответствует системе. <br>
$\begin{cases}
x_{1} + x_{2} - x_{3} -2 \cdot x_{4} = 0, \\
-x_{2} + x_{3} + 5 \cdot x_{4} = -2, \\
-\frac{2}{3} \cdot x_{3} + x_{4} = \frac{4}{3}
\end{cases}$ <br>
<br>
Бесконечное множество решений принято записывать в виде _общего решения_. <br>
Последнее уравнение содержит две неизвестных. В данном случае можно рассматривать в качестве _свободного_ параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим: <br>
$x_{4}=c,$ <br>
$x_{3}=\frac{4-3c}{-2} \;$ <br>
$x_{2}=2 + 5 \cdot c + \frac{4-3c}{-2},$ <br>
$x_{1}=-2 -3 \cdot c.$ <br>
<br>
Таковым будет _общее решение системы_. Подставляя произвольные числа вместо $c$, мы получим _частное решение_. Например, при $c=0$: <br>
$x_{1}=-2,$ <br>
$x_{2}=0,$ <br>
$x_{3}=-2,$ <br>
$x_{4}=0.$ <br>
<br>
Параметр $c$ может принимать бесконечное количество значений, при которых уравнения в системе будут обращаться в тождества.

#### Задание 2
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений: <br>

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Решение: <br>
Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$rank A=rank \tilde A.$

a)

In [2]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
result_a = np.linalg.matrix_rank(a)
result_a

3

In [3]:
b = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
result_b = np.linalg.matrix_rank(b)
result_b

3

$rangA=rang(A|B)=n$, следовательно, система совместная и определенная.

б)

In [4]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
result_a = np.linalg.matrix_rank(a)
result_a

1

In [5]:
b = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
result_b = np.linalg.matrix_rank(b)
result_b

2

$rangA$ не равен $rang(A|B)$, следовательно, система несовместная.

в)

In [6]:
a = np.array([[1, 2, 5], [3, 1, -8]])
result_a = np.linalg.matrix_rank(a)
result_a

2

In [7]:
b = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
result_b = np.linalg.matrix_rank(b)
result_b

2

$rangA=rang(A|B)<n$, следовательно, система совместная и неопределенная.

#### Задание 3
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей: <br>
$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$

Решение: <br>

In [8]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
result_a = np.linalg.matrix_rank(a)
result_a

4

In [9]:
b = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
result_b = np.linalg.matrix_rank(b)
result_b

4

$rang(A)=rang(A|B)=n$, следовательно, система совместная и определенная. <br>

#### Задание 4
Дана система линейных уравнений, заданная расширенной матрицей: <br>
$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$ <br>
<br>
Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Решение: <br>

1 строку умножим на 2 и вычтем и 2 строки. <br>
1 строку умножим на 3 и вычтем и 3 строки. <br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix}.$ <br>
<br>
2 строку умножим на 2 и вычтем из 3 строки. <br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c + a - 2b
\end{matrix}
\end{pmatrix}.$ <br>
<br>
Если $c + a - 2b \neq 0$, то система несовместна.

### Урок 4. Системы линейных уравнений. Часть 2

#### Задание 1
Решить систему уравнений методом Крамера: <br>
а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$ <br>
<br>
б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Решение: <br>

а)

Найдем определитель матрицы: <br>
$detA=\begin{vmatrix}
1 & -2\\
3 & -4\\
\end{vmatrix}=(1 \cdot -4) - (-2 \cdot 3) = 2$ <br>
<br>
Найдем определитель $detA_{1}$: <br>
$detA_{1}=\begin{vmatrix}
1 & -2\\
7 & -4\\
\end{vmatrix}=(1 \cdot -4) - (-2 \cdot 7) = 10$ <br>
<br>
Найдем определитель $detA_{2}$: <br>
$detA_{2}=\begin{vmatrix}
1 & 1\\
3 & 1\\
\end{vmatrix}=(1 \cdot 7) - (1 \cdot 3) = 4$ <br>
<br>
Найдем значения $x_{1}, x_{2}$: <br>
$x_{1}=10/2=5$ <br>
$x_{2}=4/2=2$ <br>
<br>
Проверим полученное решение: <br>
$\begin{cases}
5-4=1 \\
15-8=7
\end{cases}$

б)

Найдем определитель матрицы: <br>
$detA=\begin{vmatrix}
2 & -1 & 5\\
1 & -1 & -3\\
2 & 4 & 1
\end{vmatrix}=(2 \cdot 1 \cdot 1) + (-1 \cdot -3 \cdot 2) + (5 \cdot 1 \cdot 4) - (5 \cdot 1 \cdot 2) - (2 \cdot -3 \cdot 4) - (-1 \cdot 1 \cdot 1) = 43$ <br>
<br>
Найдем определитель $detA_{1}$: <br>
$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\
-2 & -1 & -3\\
1 & 4 & 1
\end{vmatrix}=(10 \cdot 1 \cdot 1) + (-1 \cdot -3 \cdot 1) + (5 \cdot -2 \cdot 4) - (5 \cdot 1 \cdot 1) - (10 \cdot -3 \cdot 4) - (-1 \cdot -2 \cdot 1) = 86$ <br>
<br>
Найдем определитель $detA_{2}$: <br>
$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix}=(2 \cdot -2 \cdot 1) + (10 \cdot -3 \cdot 2) + (5 \cdot 1 \cdot 1) - (5 \cdot -2 \cdot 2) - (2 \cdot -3 \cdot 1) - (10 \cdot 1 \cdot 1) = -43$ <br>
<br>
Найдем определитель $detA_{3}$: <br>
$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\
1 & -1 & -2\\
2 & 4 & 1
\end{vmatrix}=(2 \cdot 1 \cdot 1) + (-1 \cdot -2 \cdot 2) + (10 \cdot 1 \cdot 4) - (10 \cdot 1 \cdot 2) - (2 \cdot -2 \cdot 4) - (-1 \cdot 1 \cdot 1) = 43$ <br>
<br>
Найдем значения $x_{1}, x_{2}, x_{3}$: <br>
$x_{1}=86/43=2$ <br>
$x_{2}=-43/43=-1$ <br>
$x_{3}=43/43=1$ <br>
<br>
Проверим полученное решение: <br>
$\begin{cases}
4+1+5=10 \\
2-1-3=-2 \\
4-4+1=1
\end{cases}$

#### Задание 2
Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов: <br>
а) <br>
$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$ <br>
<br>
б) <br>
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

а)

In [10]:
a = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
result = decompose_to_LU(a)
result

matrix([[1., 2., 4.],
        [2., 5., 4.],
        [3., 4., 2.]])

In [11]:
L = get_L(result)
L

matrix([[1., 0., 0.],
        [2., 1., 0.],
        [3., 4., 1.]])

In [12]:
U = get_U(result)
U

matrix([[1., 2., 4.],
        [0., 5., 4.],
        [0., 0., 2.]])

б)

In [13]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
LU = decompose_to_LU(a)
LU

matrix([[1., 1., 2., 4.],
        [2., 3., 4., 1.],
        [3., 5., 3., 1.],
        [4., 6., 7., 4.]])

In [14]:
L = get_L(result)
L

matrix([[1., 0., 0.],
        [2., 1., 0.],
        [3., 4., 1.]])

In [15]:
U = get_U(result)
U

matrix([[1., 2., 4.],
        [0., 5., 4.],
        [0., 0., 2.]])

#### Задание 3
Решить систему линейных уравнений методом $LU$-разложения: <br>
$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

In [16]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([[1], [-6], [-5]])
LU = decompose_to_LU(a)
LU

matrix([[  2.        ,   1.        ,   3.        ],
        [  5.5       ,   1.5       , -11.5       ],
        [  4.5       ,   2.33333333,  17.33333333]])

In [17]:
result = solve_LU(LU, b)
result

matrix([[-1.],
        [ 0.],
        [ 1.]])

#### Задание 4
Решить систему линейных уравнений методом Холецкого: <br>
$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

Решение: <br>

Находим элементы матрицы L. <br>
$l_{11} = \sqrt{81} = 9$ <br>
$l_{22} = \sqrt{50 - (-5)^2} = 5$ <br>
$l_{33} = \sqrt{38 - 5^2 - 2^2} = 3$ <br>
$l_{21} = \frac{-45}{9} = -5$ <br>
$l_{32} = \frac{-15 - 5 * (-5)}{5} = 2$ <br>
$l_{31} = \frac{45}{9} = 5$

Таким образом разложение матрицы A имеет вид: <br>
$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$

Последовательно решаем системы: <br>
$L * y = b$ <br>
$L^{T} * x = y$

Решением 1-ой системы является вектор: <br>
$y = \begin{pmatrix}
59 \\ 
-33 \\ 
-12
\end{pmatrix}$

Решением 2-ой системы является вектор: <br>
$x = \begin{pmatrix}
6 \\ 
-5 \\ 
-4
\end{pmatrix}$

Ответ: <br>
$x_{1} = 6$ <br>
$x_{2} = -5$ <br>
$x_{3} = -4$